services:
  measurement-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: measurement-app
    restart: always
    ports:
      - "4202:4202"
    environment:
      NODE_ENV: production
      PORT: 4202
